### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by amoraschi**
Small typo, but an important one

### CODE REVIEW

**Comment by aes0002** [comment]
lgtm

**Review by aes0002 — APPROVED** [review]

**Comment by Peletic** [comment]
very important!!

**Comment by Zn10plays** [comment]
An improper citation is as bad as plagiarism. 

Good job! LGTM

**Comment by Ekwav** [comment]
Thats not a typo, thats the intended name

**Comment by aesthetic0001** [comment]
😭

**Comment by Ekwav** [comment]
This has to be the most "active" thread on any of my repositories

**Pull request closed without merging**
